# fly.toml file generated for goldenlinden on 2023-03-17T23:29:42-04:00

app = "goldenlinden"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ewr"
processes = []

[build]
  image = "mimonn/goldenlinden:latest"

[env]
	ASPNETCORE_URLS="http://+:8080"
	StripeSettings__PublishableKey="pk_test_51MhZrbLunxQjCbLSJ4fWmoD7UCoWvzO1hh5NsWbZYdapCR809D8bArdmnQMLk5NKbjjPOIfrriFObQLCU3QmDxmF00coOmUHka"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
